version: '1.0'

networks:
  reservation-network: 
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
services:
  db:
    image: postgres:16.3
    container_name: postgresql
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: postgres_pw
      POSTGRES_DB: exam
    volumes:
      #- /Users/work6189/Documents/project/db/postgres_data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      reservation-network:
        ipv4_address: 192.168.56.11

  web:
    build : .
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://web:postgres_pw@db:5432/exam
    networks:
      reservation-network:
        ipv4_address: 192.168.56.111

